# Generated by Django 4.2.7 on 2023-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('autor', models.CharField(max_length=50, verbose_name='autor')),
                ('editora', models.CharField(max_length=30, verbose_name='editora')),
                ('ano_pub', models.PositiveSmallIntegerField(verbose_name='ano de publicação')),
                ('num_pag', models.PositiveSmallIntegerField(verbose_name='número de páginas')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
